-- ================================================================
-- PROYECTO FINAL: ZOO SAFARI — Gestion Integral del Safari
-- Asignatura: Bases de Datos Avanzadas
-- Equipo:
--   David Pacanchique  — Arquitecto de Datos
--   Alan Melo Giraldo  — Desarrollador PL/SQL
--   Darian Molina      — Lider de QA
-- Herramienta: Oracle Live SQL (livesql.oracle.com)
-- Fecha: Junio 2025
-- ================================================================
-- AUTOEVALUACION (marcar antes de entregar):
-- [X] 1. A-DDL: 9 tablas con FK y CHECK constraints
-- [X] 2. A-DDL: Script de limpieza (DROP seguro)
-- [X] 3. A-DDL: Minimo 10 filas por tabla principal
-- [X] 4. B-ACID: Bloque NOWAIT con PRAGMA (-54)
-- [X] 5. B-ACID: Bloque WAIT con PRAGMA (-30006)
-- [X] 6. B-ACID: COMMIT y ROLLBACK en cada escenario
-- [X] 7. C-PL/SQL: Trigger BEFORE INSERT con :NEW y RAISE_APPLICATION_ERROR
-- [X] 8. C-PL/SQL: Pruebas del Trigger (caso OK y caso fallo)
-- [X] 9. C-PL/SQL: Stored Procedure con 2+ DMLs y EXCEPTION
-- [X] 10. D-Vistas: Vista de seguridad sin columnas sensibles
-- [X] 11. D-Vistas: Vista de reporte con JOIN + GROUP BY + SUM/COUNT
-- [X] 12. Transversal: Archivo .sql unico
-- ================================================================


-- ==================================================
-- BLOQUE 0: LIMPIEZA — permite re-ejecucion segura
-- Orden inverso a la creacion (hijos antes que padres)
-- ==================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE avistamiento CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE recorrido CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE animal CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE carrito CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE guia CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE visitante CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE empleado CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE especie CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE zona CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_validar_capacidad_recorrido'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE registrar_recorrido_completo'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ==================================================
-- COMPONENTE A: DDL — TABLAS, FK Y CHECK CONSTRAINTS
-- ==================================================

-- Tabla 1: zona (sin dependencias, va primero)
CREATE TABLE zona (
    id_zona     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(500)
);

-- Tabla 2: especie
CREATE TABLE especie (
    id_especie  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(120) NOT NULL,
    tipo        VARCHAR2(60),
    dieta       VARCHAR2(40),
    peligro_ext VARCHAR2(60),
    CONSTRAINT chk_dieta CHECK (dieta IN ('Carnivoro','Herbivoro','Omnivoro','Insectivoro','Piscivoro')),
    CONSTRAINT chk_peligro CHECK (peligro_ext IN ('Preocupacion menor','Casi amenazado','Vulnerable',
                                                   'En peligro','En peligro critico','Extinto en estado silvestre','Extinto'))
);

-- Tabla 3: animal
CREATE TABLE animal (
    id_animal        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(100) NOT NULL,
    sexo             CHAR(1)       NOT NULL,
    fecha_nacimiento DATE,
    procedencia      VARCHAR2(150),
    estado           VARCHAR2(30)  DEFAULT 'Saludable',
    id_especie       NUMBER        NOT NULL,
    id_zona          NUMBER        NOT NULL,
    CONSTRAINT fk_animal_especie FOREIGN KEY (id_especie) REFERENCES especie(id_especie),
    CONSTRAINT fk_animal_zona    FOREIGN KEY (id_zona)    REFERENCES zona(id_zona),
    CONSTRAINT chk_sexo_animal   CHECK (sexo IN ('M','F')),
    CONSTRAINT chk_estado_animal CHECK (estado IN ('Saludable','En tratamiento','En cuarentena','Fallecido'))
);

-- Tabla 4: visitante
CREATE TABLE visitante (
    id_visitante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(120) NOT NULL,
    correo       VARCHAR2(150) UNIQUE,
    telefono     VARCHAR2(25),
    pais         VARCHAR2(80)
);

-- Tabla 5: carrito
CREATE TABLE carrito (
    id_carrito NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo     VARCHAR2(20) NOT NULL UNIQUE,
    capacidad  NUMBER       NOT NULL,
    tipo       VARCHAR2(80),
    estado     VARCHAR2(30) DEFAULT 'Disponible',
    CONSTRAINT chk_capacidad_positiva CHECK (capacidad > 0),
    CONSTRAINT chk_estado_carrito     CHECK (estado IN ('Disponible','En uso','Mantenimiento'))
);

-- Tabla 6: guia
CREATE TABLE guia (
    id_guia          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(120) NOT NULL,
    idiomas          VARCHAR2(200),
    telefono         VARCHAR2(25),
    experiencia_anos NUMBER        DEFAULT 0,
    CONSTRAINT chk_experiencia CHECK (experiencia_anos >= 0)
);

-- Tabla 7: recorrido
CREATE TABLE recorrido (
    id_recorrido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha        DATE          NOT NULL DEFAULT SYSDATE,
    hora_inicio  VARCHAR2(8),
    hora_fin     VARCHAR2(8),
    num_personas NUMBER        DEFAULT 1,
    total_pagado NUMBER(12,2)  DEFAULT 0,
    estado       VARCHAR2(30)  DEFAULT 'Reservado',
    id_visitante NUMBER        NOT NULL,
    id_carrito   NUMBER        NOT NULL,
    id_guia      NUMBER        NOT NULL,
    CONSTRAINT fk_recorrido_visitante FOREIGN KEY (id_visitante) REFERENCES visitante(id_visitante),
    CONSTRAINT fk_recorrido_carrito   FOREIGN KEY (id_carrito)   REFERENCES carrito(id_carrito),
    CONSTRAINT fk_recorrido_guia      FOREIGN KEY (id_guia)      REFERENCES guia(id_guia),
    CONSTRAINT chk_personas_positivas CHECK (num_personas > 0),
    CONSTRAINT chk_total_positivo     CHECK (total_pagado >= 0),
    CONSTRAINT chk_estado_recorrido   CHECK (estado IN ('Reservado','Completado','Cancelado'))
);

-- Tabla 8: avistamiento
CREATE TABLE avistamiento (
    id_avistamiento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recorrido    NUMBER        NOT NULL,
    id_animal       NUMBER        NOT NULL,
    hora            VARCHAR2(8),
    comportamiento  VARCHAR2(100),
    notas           VARCHAR2(500),
    CONSTRAINT fk_avistamiento_recorrido FOREIGN KEY (id_recorrido) REFERENCES recorrido(id_recorrido),
    CONSTRAINT fk_avistamiento_animal    FOREIGN KEY (id_animal)    REFERENCES animal(id_animal)
);

-- Tabla 9: empleado
CREATE TABLE empleado (
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(120) NOT NULL,
    cargo       VARCHAR2(80),
    salario     NUMBER(12,2),
    telefono    VARCHAR2(25),
    CONSTRAINT chk_salario_positivo CHECK (salario > 0)
);


-- ==================================================
-- DATOS DE PRUEBA — minimo 10 filas por tabla
-- ==================================================

INSERT INTO zona (nombre, descripcion) VALUES ('Gran Sabana',       'Extensa planicie con leones, elefantes y jirafas. Zona estrella del safari.');
INSERT INTO zona (nombre, descripcion) VALUES ('Bosque Ecuatorial', 'Zona humeda con primates, aves exoticas y grandes felinos.');
INSERT INTO zona (nombre, descripcion) VALUES ('Laguna Africana',   'Espejo de agua con hipopotamos, cocodrilos y flamencos.');
INSERT INTO zona (nombre, descripcion) VALUES ('Pradera del Este',  'Zona abierta con cebras, nuus y guepardos.');
INSERT INTO zona (nombre, descripcion) VALUES ('Noche Salvaje',     'Recorrido nocturno con animales de habitos nocturnos.');

INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Leon africano',       'Mamifero', 'Carnivoro',  'Vulnerable');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Elefante africano',   'Mamifero', 'Herbivoro',  'Vulnerable');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Jirafa',              'Mamifero', 'Herbivoro',  'Vulnerable');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Cebra de Burchell',   'Mamifero', 'Herbivoro',  'Preocupacion menor');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Chimpance',           'Mamifero', 'Omnivoro',   'En peligro');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Cocodrilo del Nilo',  'Reptil',   'Carnivoro',  'Preocupacion menor');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Flamenco rosa',       'Ave',      'Omnivoro',   'Preocupacion menor');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Gorila de montana',   'Mamifero', 'Herbivoro',  'En peligro critico');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Guepardo',            'Mamifero', 'Carnivoro',  'Vulnerable');
INSERT INTO especie (nombre, tipo, dieta, peligro_ext) VALUES ('Hipopotamo',          'Mamifero', 'Herbivoro',  'Vulnerable');

INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Simba',   'M', DATE '2015-03-10', 'Nacido en cautiverio', 'Saludable',     1, 1);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Nala',    'F', DATE '2016-07-22', 'Nacido en cautiverio', 'Saludable',     1, 1);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Flash',   'M', DATE '2018-01-05', 'Rescate',              'Saludable',     1, 1);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Mufasa',  'M', DATE '2010-11-30', 'Donacion zoo Berlin',  'En tratamiento',1, 1);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Rex',     'M', DATE '2014-06-18', 'Rescate',              'Saludable',     6, 3);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Daisy',   'F', DATE '2017-02-14', 'Nacido en cautiverio', 'Saludable',     6, 3);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Goliat',  'M', DATE '2012-09-01', 'Donacion',             'Saludable',     3, 1);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Coco',    'F', DATE '2019-04-20', 'Nacido en cautiverio', 'Saludable',     5, 2);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Kong',    'M', DATE '2013-08-15', 'Rescate',              'En tratamiento',8, 2);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Sheba',   'F', DATE '2016-12-03', 'Nacido en cautiverio', 'Saludable',     8, 2);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Alpha',   'M', DATE '2017-05-25', 'Rescate',              'Saludable',     9, 4);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Beta',    'F', DATE '2018-03-11', 'Nacido en cautiverio', 'Saludable',     9, 4);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Eva',     'F', DATE '2020-01-30', 'Nacido en cautiverio', 'Saludable',     5, 2);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Bahati',  'F', DATE '2014-07-07', 'Donacion',             'Saludable',     2, 1);
INSERT INTO animal (nombre, sexo, fecha_nacimiento, procedencia, estado, id_especie, id_zona) VALUES ('Tembo',   'M', DATE '2011-11-11', 'Donacion zoo Paris',   'Saludable',     2, 1);

INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Sofia Gutierrez',   'sofia@test.com',    '3001234567', 'Colombia');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Carlos Restrepo',   'carlos@test.com',   '3109876543', 'Colombia');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Valentina Ospina',  'vale@test.com',     '3204561234', 'Colombia');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('James Wilson',      'james@test.com',    '5551234567', 'USA');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Marie Dupont',      'marie@test.com',    '0033789456', 'Francia');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Lucia Martinez',    'lucia@test.com',    '3015557890', 'Colombia');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Pedro Rojas',       'pedro@test.com',    '3123456789', 'Colombia');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Anna Schmidt',      'anna@test.com',     '004915123',  'Alemania');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Tomoko Nakamura',   'tomoko@test.com',   '0081312345', 'Japon');
INSERT INTO visitante (nombre, correo, telefono, pais) VALUES ('Ibrahim Diallo',    'ibrahim@test.com',  '002212345',  'Senegal');

INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-01', 8,  'Jeep 4x4',          'Disponible');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-02', 12, 'Bus panoramico',    'Disponible');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-03', 6,  'Electrico VIP',     'Disponible');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-04', 8,  'Jeep 4x4',          'Mantenimiento');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-05', 10, 'Bus panoramico',    'Disponible');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-06', 4,  'Electrico VIP',     'Disponible');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-07', 8,  'Jeep 4x4',          'Disponible');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-08', 15, 'Bus escolar',       'Disponible');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-09', 6,  'Electrico VIP',     'En uso');
INSERT INTO carrito (codigo, capacidad, tipo, estado) VALUES ('SAF-10', 8,  'Jeep 4x4 nocturno', 'Disponible');

INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Andres Vargas',   'Espanol, Ingles',           '3001112222', 8);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Laura Torres',    'Espanol, Frances',          '3003334444', 5);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Miguel Sanchez',  'Espanol, Ingles, Aleman',   '3005556666', 12);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Juliana Gomez',   'Espanol, Portugues',        '3007778888', 3);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Rafael Mendez',   'Espanol, Ingles',           '3009990000', 7);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Camila Rios',     'Espanol, Japones, Ingles',  '3011231234', 6);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Samuel Ortiz',    'Espanol',                   '3024564567', 4);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Natalia Cruz',    'Espanol, Ingles, Frances',  '3037897890', 9);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Jorge Pena',      'Espanol, Italiano',         '3041011012', 11);
INSERT INTO guia (nombre, idiomas, telefono, experiencia_anos) VALUES ('Diana Morales',   'Espanol, Ingles',           '3051131134', 2);

INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-10', '08:00:00', '10:30:00', 4, 320000, 'Completado', 1, 1, 1);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-11', '09:00:00', '11:30:00', 6, 480000, 'Completado', 2, 2, 2);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-12', '10:00:00', '13:00:00', 3, 240000, 'Completado', 3, 3, 3);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-13', '08:30:00', '11:00:00', 5, 400000, 'Completado', 4, 1, 4);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-14', '14:00:00', '16:30:00', 2, 160000, 'Completado', 5, 5, 5);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-15', '09:00:00', '12:00:00', 8, 640000, 'Completado', 6, 2, 6);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-16', '20:00:00', '22:00:00', 4, 520000, 'Completado', 7, 7, 7);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-17', '08:00:00', '10:30:00', 3, 240000, 'Reservado',  8, 3, 8);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-18', '11:00:00', '14:00:00', 6, 480000, 'Cancelado',  9, 5, 9);
INSERT INTO recorrido (fecha, hora_inicio, hora_fin, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
VALUES (DATE '2025-05-19', '09:30:00', '12:30:00', 4, 320000, 'Reservado',  10, 6, 10);

INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (1, 1,  '08:40:00', 'Descansando',    'Simba echado bajo una acacia con la manada');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (1, 3,  '09:05:00', 'Caminando',      'Mufasa liderando el grupo hacia el agua');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (1, 8,  '08:55:00', 'Corriendo',      'Flash en persecucion corta de un impala');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (2, 14, '09:40:00', 'En movimiento',  'Manada de cebras cruzando la pista');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (2, 15, '10:00:00', 'Pastando',       'Grupo de nus en la llanura abierta');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (3, 5,  '11:00:00', 'En el agua',     'Rex semisubmergido con Daisy y el bebe');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (3, 7,  '10:50:00', 'Tomando sol',    'Croc con la boca abierta en la orilla');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (4, 7,  '08:30:00', 'Alimentandose',  'Goliat comiendo hojas del arbol mas alto');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (5, 8,  '15:20:00', 'Jugando',        'Coco trepando arboles con Eva');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (5, 10, '15:40:00', 'Descansando',    'Kong descansando en el suelo con Sheba');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (6, 11, '09:10:00', 'Volando',        'Colonia de flamencos levantando vuelo');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (7, 11, '20:30:00', 'Patrullando',    'Alpha y Beta marcando territorio de noche');
INSERT INTO avistamiento (id_recorrido, id_animal, hora, comportamiento, notas) VALUES (7, 1,  '20:45:00', 'Rugiendo',       'Simba rugiendo en la oscuridad');

INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Dr. Fernando Vega',    'Veterinario jefe',   5800000, '3111112222');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Dra. Paola Suarez',    'Veterinaria',        4500000, '3123334444');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Lucas Herrera',        'Guardabosque',       2800000, '3135556666');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Monica Parra',         'Guardabosque',       2800000, '3147778888');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Esteban Gil',          'Mecanico',           3200000, '3159990000');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Rosa Jimenez',         'Recepcion',          2400000, '3161231234');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Carlos Benitez',       'Guardabosque',       2800000, '3174564567');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Adriana Castro',       'Cuidadora animales', 3100000, '3187897890');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Jorge Salazar',        'Mecanico',           3200000, '3191011012');
INSERT INTO empleado (nombre, cargo, salario, telefono) VALUES ('Patricia Leal',        'Cuidadora animales', 3100000, '3201131134');

COMMIT;

SELECT 'zona'          AS tabla, COUNT(*) AS filas FROM zona         UNION ALL
SELECT 'especie',                COUNT(*)           FROM especie      UNION ALL
SELECT 'animal',                 COUNT(*)           FROM animal       UNION ALL
SELECT 'visitante',              COUNT(*)           FROM visitante    UNION ALL
SELECT 'carrito',                COUNT(*)           FROM carrito      UNION ALL
SELECT 'guia',                   COUNT(*)           FROM guia         UNION ALL
SELECT 'recorrido',              COUNT(*)           FROM recorrido    UNION ALL
SELECT 'avistamiento',           COUNT(*)           FROM avistamiento UNION ALL
SELECT 'empleado',               COUNT(*)           FROM empleado;


-- ==================================================
-- COMPONENTE B: ACID Y CONTROL DE CONCURRENCIA
-- ==================================================

-- ESCENARIO 1: FOR UPDATE NOWAIT (PRAGMA -54)
DECLARE
    v_estado_carrito VARCHAR2(30);
    v_codigo         VARCHAR2(20);
    v_id_carrito     NUMBER := 1;
    CARRITO_BLOQUEADO EXCEPTION;
    PRAGMA EXCEPTION_INIT(CARRITO_BLOQUEADO, -54);
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== ESCENARIO NOWAIT: Reservando carrito SAF-01 ===');
    SELECT codigo, estado
    INTO   v_codigo, v_estado_carrito
    FROM   carrito
    WHERE  id_carrito = v_id_carrito
    FOR UPDATE NOWAIT;
    DBMS_OUTPUT.PUT_LINE('Lock obtenido: Carrito ' || v_codigo || ' | Estado: ' || v_estado_carrito);
    IF v_estado_carrito = 'Disponible' THEN
        UPDATE carrito SET estado = 'En uso' WHERE id_carrito = v_id_carrito;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('EXITO: Carrito ' || v_codigo || ' asignado. Estado -> En uso.');
    ELSE
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('RECHAZADO: Estado actual ' || v_estado_carrito);
    END IF;
EXCEPTION
    WHEN CARRITO_BLOQUEADO THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ALERTA: Carrito bloqueado por otra sesion (ORA-00054). ROLLBACK ejecutado.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR CRITICO: ' || SQLERRM);
END;
/

UPDATE carrito SET estado = 'Disponible' WHERE id_carrito = 1;
COMMIT;

-- ESCENARIO 2: FOR UPDATE WAIT 4 (PRAGMA -30006)
DECLARE
    v_estado_carrito VARCHAR2(30);
    v_id_carrito     NUMBER := 1;
    TIMEOUT_EXPIRADO EXCEPTION;
    PRAGMA EXCEPTION_INIT(TIMEOUT_EXPIRADO, -30006);
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== ESCENARIO WAIT 4: Esperando hasta 4 segundos por SAF-01 ===');
    SELECT estado INTO v_estado_carrito
    FROM   carrito
    WHERE  id_carrito = v_id_carrito
    FOR UPDATE WAIT 4;
    DBMS_OUTPUT.PUT_LINE('Lock obtenido. Estado: ' || v_estado_carrito);
    IF v_estado_carrito = 'Disponible' THEN
        UPDATE carrito SET estado = 'En uso' WHERE id_carrito = v_id_carrito;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('EXITO: Carrito reservado correctamente.');
    ELSE
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('RECHAZADO: Carrito no disponible. Estado: ' || v_estado_carrito);
    END IF;
EXCEPTION
    WHEN TIMEOUT_EXPIRADO THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('TIMEOUT: Carrito no liberado en 4 segundos (ORA-30006). ROLLBACK ejecutado.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END;
/

UPDATE carrito SET estado = 'Disponible' WHERE id_carrito = 1;
COMMIT;


-- ==================================================
-- COMPONENTE C: PL/SQL — TRIGGER Y STORED PROCEDURE
-- ==================================================

-- TRIGGER: trg_validar_capacidad_recorrido
BEGIN
    EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER trg_validar_capacidad_recorrido
    BEFORE INSERT ON recorrido
    FOR EACH ROW
DECLARE
    v_capacidad    NUMBER;
    v_estado_carr  VARCHAR2(30);
    v_codigo_carr  VARCHAR2(20);
BEGIN
    SELECT capacidad, estado, codigo
    INTO   v_capacidad, v_estado_carr, v_codigo_carr
    FROM   carrito
    WHERE  id_carrito = :NEW.id_carrito;

    IF v_estado_carr != ''Disponible'' THEN
        RAISE_APPLICATION_ERROR(-20002,
            ''Carrito '' || v_codigo_carr || '' no esta Disponible. Estado actual: '' || v_estado_carr);
    END IF;

    IF :NEW.num_personas > v_capacidad THEN
        RAISE_APPLICATION_ERROR(-20001,
            ''Capacidad excedida en carrito '' || v_codigo_carr ||
            ''. Capacidad maxima: '' || v_capacidad ||
            ''. Personas solicitadas: '' || :NEW.num_personas);
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003,
            ''Carrito ID '' || :NEW.id_carrito || '' no existe en el sistema.'');
END trg_validar_capacidad_recorrido';
    DBMS_OUTPUT.PUT_LINE('Trigger trg_validar_capacidad_recorrido creado OK.');
END;
/

SELECT object_name, status FROM user_objects WHERE object_name = 'TRG_VALIDAR_CAPACIDAD_RECORRIDO';

-- PRUEBA TRIGGER 1: Caso OK
BEGIN
    INSERT INTO recorrido (fecha, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
    VALUES (SYSDATE, 5, 400000, 'Reservado', 1, 1, 1);
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('PRUEBA TRIGGER 1 OK: Insert valido aceptado.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA TRIGGER 1 ERROR inesperado: ' || SQLERRM);
END;
/

-- PRUEBA TRIGGER 2: Capacidad excedida
BEGIN
    INSERT INTO recorrido (fecha, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
    VALUES (SYSDATE, 50, 4000000, 'Reservado', 1, 3, 1);
    DBMS_OUTPUT.PUT_LINE('PRUEBA TRIGGER 2 ERROR: El Trigger no rechazo la capacidad excedida!');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA TRIGGER 2 OK: ' || SQLERRM);
END;
/

-- PRUEBA TRIGGER 3: Carrito en Mantenimiento
BEGIN
    INSERT INTO recorrido (fecha, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
    VALUES (SYSDATE, 3, 240000, 'Reservado', 2, 4, 2);
    DBMS_OUTPUT.PUT_LINE('PRUEBA TRIGGER 3 ERROR: El Trigger no rechazo el carrito no disponible!');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA TRIGGER 3 OK: ' || SQLERRM);
END;
/


-- STORED PROCEDURE: registrar_recorrido_completo
CREATE OR REPLACE PROCEDURE registrar_recorrido_completo(
    p_visitante_id   IN NUMBER,
    p_carrito_id     IN NUMBER,
    p_guia_id        IN NUMBER,
    p_num_personas   IN NUMBER,
    p_precio_persona IN NUMBER
) IS
    v_nombre_vis   VARCHAR2(120);
    v_codigo_carr  VARCHAR2(20);
    v_capacidad    NUMBER;
    v_estado_carr  VARCHAR2(30);
    v_nombre_guia  VARCHAR2(120);
    v_total        NUMBER(12,2);
    v_nuevo_id     NUMBER;
BEGIN
    SELECT nombre INTO v_nombre_vis FROM visitante WHERE id_visitante = p_visitante_id;
    SELECT codigo, capacidad, estado INTO v_codigo_carr, v_capacidad, v_estado_carr
    FROM   carrito WHERE id_carrito = p_carrito_id;

    IF v_estado_carr != 'Disponible' THEN
        RAISE_APPLICATION_ERROR(-20010, 'Carrito ' || v_codigo_carr || ' no disponible. Estado: ' || v_estado_carr);
    END IF;
    IF p_num_personas > v_capacidad THEN
        RAISE_APPLICATION_ERROR(-20011, 'Capacidad excedida: ' || v_codigo_carr || ' max ' || v_capacidad || ' personas.');
    END IF;
    IF p_num_personas <= 0 THEN
        RAISE_APPLICATION_ERROR(-20012, 'El numero de personas debe ser mayor a cero.');
    END IF;

    SELECT nombre INTO v_nombre_guia FROM guia WHERE id_guia = p_guia_id;
    v_total := p_num_personas * p_precio_persona;

    INSERT INTO recorrido (fecha, hora_inicio, num_personas, total_pagado, estado, id_visitante, id_carrito, id_guia)
    VALUES (SYSDATE, TO_CHAR(SYSDATE,'HH24:MI:SS'), p_num_personas, v_total, 'Reservado', p_visitante_id, p_carrito_id, p_guia_id)
    RETURNING id_recorrido INTO v_nuevo_id;

    UPDATE carrito SET estado = 'En uso' WHERE id_carrito = p_carrito_id;
    COMMIT;

    DBMS_OUTPUT.PUT_LINE('=== RECORRIDO #' || v_nuevo_id || ' CREADO ===');
    DBMS_OUTPUT.PUT_LINE('Visitante: ' || v_nombre_vis || ' | Guia: ' || v_nombre_guia);
    DBMS_OUTPUT.PUT_LINE('Carrito: ' || v_codigo_carr || ' | Personas: ' || p_num_personas);
    DBMS_OUTPUT.PUT_LINE('Total: $ ' || TO_CHAR(v_total,'999,999,999'));
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: Visitante, carrito o guia no encontrado.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END registrar_recorrido_completo;
/

SELECT object_name, status FROM user_objects WHERE object_name = 'REGISTRAR_RECORRIDO_COMPLETO';

-- PRUEBA A: Caso exitoso
EXEC registrar_recorrido_completo(p_visitante_id=>8, p_carrito_id=>7, p_guia_id=>8, p_num_personas=>5, p_precio_persona=>80000);

-- PRUEBA B: Capacidad excedida
EXEC registrar_recorrido_completo(p_visitante_id=>9, p_carrito_id=>6, p_guia_id=>9, p_num_personas=>20, p_precio_persona=>80000);

-- PRUEBA C: Carrito no disponible
EXEC registrar_recorrido_completo(p_visitante_id=>10, p_carrito_id=>9, p_guia_id=>10, p_num_personas=>3, p_precio_persona=>80000);


-- ==================================================
-- COMPONENTE D: VISTAS
-- ==================================================

-- VISTA 1 DE SEGURIDAD: v_ficha_publica_animal
CREATE OR REPLACE VIEW v_ficha_publica_animal AS
SELECT
    a.id_animal,
    a.nombre                                      AS animal,
    a.sexo,
    FLOOR(MONTHS_BETWEEN(SYSDATE, a.fecha_nacimiento) / 12) AS edad_anos,
    e.nombre                                      AS especie,
    e.tipo                                        AS tipo_animal,
    e.dieta,
    e.peligro_ext                                 AS estado_conservacion,
    z.nombre                                      AS zona_safari,
    CASE
        WHEN a.estado = 'Saludable'        THEN 'Activo para avistamiento'
        WHEN a.estado = 'En tratamiento'   THEN 'Temporalmente fuera de ruta'
        WHEN a.estado = 'En cuarentena'    THEN 'No disponible'
        ELSE                                    'Informacion no disponible'
    END                                           AS disponibilidad_publica
FROM animal  a
JOIN especie e ON a.id_especie = e.id_especie
JOIN zona    z ON a.id_zona    = z.id_zona
WHERE a.estado != 'Fallecido';

SELECT * FROM v_ficha_publica_animal ORDER BY zona_safari, especie;

-- VISTA 2 DE REPORTE: v_reporte_recorridos_por_guia
CREATE OR REPLACE VIEW v_reporte_recorridos_por_guia AS
SELECT
    g.nombre                                      AS guia,
    g.idiomas,
    g.experiencia_anos,
    COUNT(r.id_recorrido)                         AS total_recorridos,
    SUM(r.num_personas)                           AS total_visitantes_atendidos,
    SUM(r.total_pagado)                           AS ingresos_generados,
    ROUND(AVG(r.total_pagado), 0)                 AS promedio_por_recorrido,
    ROUND(AVG(r.num_personas), 1)                 AS promedio_personas,
    MAX(r.fecha)                                  AS ultimo_recorrido,
    COUNT(DISTINCT av.id_avistamiento)            AS avistamientos_registrados
FROM guia g
JOIN recorrido    r  ON g.id_guia      = r.id_guia
JOIN avistamiento av ON r.id_recorrido = av.id_recorrido
WHERE r.estado = 'Completado'
GROUP BY g.nombre, g.idiomas, g.experiencia_anos
ORDER BY ingresos_generados DESC;

SELECT * FROM v_reporte_recorridos_por_guia;

SELECT guia, total_recorridos, ingresos_generados
FROM   v_reporte_recorridos_por_guia
WHERE  experiencia_anos > 5;


-- ==================================================
-- VERIFICACION FINAL
-- ==================================================
SELECT object_name, object_type, status
FROM   user_objects
WHERE  object_type IN ('TABLE','TRIGGER','PROCEDURE','VIEW')
AND    status = 'INVALID';

SELECT object_name, object_type, status
FROM   user_objects
WHERE  object_type IN ('TABLE','TRIGGER','PROCEDURE','VIEW')
ORDER  BY object_type, object_name;
